var annotList = {"intro":"<span class=\"annotation\"><i>Introduction.</i>  This and the next poem in the collections of 1645 and 1673 (<a href=\"../another/text.shtml\" target=\"main\">\"Another on the same\"</a>) are Milton\'s contributions to  the Hobson jest poems popular on campus at Cambridge University after the death of Thomas Hobson on January 1, 1631.  Hobson was eighty-six when he died and he had served the university for over sixty years by driving a regular coach between The Bull, a London inn, and the University, carrying students, guests, letters, and sometimes parents.  He also hired out horses.  The expression \"Hobson\'s choice\" originated as a sarcastic reference to Hobson\'s insistence that anyone hiring a horse must \"choose\" the one closest to the stable door.</p><p>Milton\'s second Hobson poem, <a href=\"../another/text.shtml\" target=\"main\">\"Another on the same,\"</a> appeared with another Hobson poem, called \"Hobsons Epitaph,\" in a collection called <a href=\"http://wwwlib.umi.com/eebo/image/13794/70\" target=\"main\"><span class=\"booktitle\">A Banquet of Jests. Or A Collection of Court. Camp. Colledge. Citie, Country Iests</span></a>  (London 1640) pages 129-132.  A 1657 edition of much the same book, now called <a href=\"http://wwwlib.umi.com/eebo/image/55914/45\" target=\"main\"><span class=\"booktitle\">A Banquet of Jests New and Old Or Change of Cheare</span></a> (London, 1657) printed both poems again with some changes on pages 82-84.  Milton\'s first Hobson poem was republished along with the others as \"Another\" in <a href=\"http://wwwlib.umi.com/eebo/image/93926/45\" target=\"main\"><span class=\"booktitle\">Wit Restor\'d In severall Select Poems Not formerly publish\'t</span></a>  (London 1658) pages 83-84.   These are all collections of jokes, ribald stories, and satires based on stereotypes of women, servingmen, lawyers, clerics, and others.  The unattributed Hobson poem that appears in all the  collections mentioned above may also, suggested W. R. Parker (<span class=\"booktitle\">Modern Language Review </span>31 [1936]: 395-402), be Milton\'s, though Milton never chose to include it in either the 1645 or 1673 collections.  The copytext for the present edition is <a href=\"http://wwwlib.umi.com/eebo/image/114721/19\" target=\"main\">1645</a>.</span>",
"vacancy":"<span class=\"annotation\"><i>vacancy.</i>  Vacation, or cessation of duties.  Much of the humor of the poem depends on the fanciful notion that Hobson would not have died if he had just kept jogging on with his rounds between London and Cambridge; he died because he was made to stop, and he stopped because he was forbiddden to ride to London and back while the plague ravaged London.</span>",
"girt":"<span class=\"annotation\"><i>girt.</i>  Girth.</span>",
"and":"<span class=\"annotation\"><i>And.</i>  <a href=\"http://wwwlib.umi.com/eebo/image/114721/19\" target=\"main\">1645</a> reads \"A here alas\";  like most editors I have adopted the <a href=\"http://wwwlib.umi.com/eebo/image/60223/21\" target=\"main\">1673</a> reading on the conviction that 1645 is an error.</span>",
"shifter":"<span class=\"annotation\"><i>shifter.</i>  Trickster; in this case he has outmaneuvered death for a long while.  The word also puns on the sense of shifter as one who moves things from place to place, or is in constant motion.</span>",
"bull":"<span class=\"annotation\"><i>the Bull.</i>  The Bull Inn, Bishopsgate, was Hobson\'s London terminus.</span>",
"faild":"<span class=\"annotation\"><i>fail\'d.</i>  Hobson\'s regular rounds were ordered stopped in 1630, due to plague.</span>",
"tane":"<span class=\"annotation\"><i>tane up.</i>  \"Taken up,\" as in \"taken a room at the last inn\" he reached.</span>",
"Chamberlin":"<span class=\"annotation\"><i>Chamberlin.</i>  An attendant in charge of the bedchambers at an inn.  \"Death\" in line 9 is the subject of this long sentence whose verb is \"Shew\'d\" in line 15, and is imagined as \"in the kind office of a Chamberlin.\"</p></div></body> </html> </span>"}
