var annotList = {"intro":"<span class=\"annotation\"><i>Introduction.</i> Psalm translations, from Hebrew, Greek (<a href=\"http://spindleworks.com/septuagint/Psalms.htm\" target=\"main\">the Septuagint</a>) and Latin (<a href=\"http://www.thelatinlibrary.com/bible/psalms.html\" target=\"main\">the Vulgate</a>), were not unusal school  exercises.  Milton certainly performed such exercises (see his <a href=\"../../paraphrase_114/text.shtml\" target=\"main\">paraphrase on Psalm 114</a>), but many of the translations published in the <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition of <span class=\"booktitle\">Poems</span></a> appear to have been done as much for devotional as for linguistic exercise.  Certainly Milton also took pride in the breadth of metrical virtuosity displayed in these verse translations.</p><p>It is instructive to  compare Milton\'s translation with those of the <a href=\"http://bible.gospelcom.net/bible?language=English&amp;version=KJV&amp;passage=Psalms+83\" target=\"main\">King James Version</a> and the <a href=\"http://ccel.org/g/geneva/notes/Psalms/83.html\" target=\"main\">Geneva</a>.  Also interesting to compare is the  <a href=\"http://www.cgmusic.com/workshop/oldver/psalm_83.htm\" target=\"main\">Thomas Sternhold and John Hopkins version</a> of 1562.</p><p>Italics indicate words that Milton has inserted to smooth out both the sense and the meter.  According to Milton, \"all but what is in a different Character, are the very words of the text, translated from the Original.\"</span>",
"jehemajun":"<span class=\"annotation\"><i>Jehemajun.</i> The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"jagnarimu":"<span class=\"annotation\"><i>Jagnarimu.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"sod":"<span class=\"annotation\"><i>Sod.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"jith":"<span class=\"annotation\"><i>Jithjagnatsu gnal.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"tseph":"<span class=\"annotation\"><i>Tsephuneca.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"lev":"<span class=\"annotation\"><i>Lev jachdau.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/80\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"neoth":"<span class=\"annotation\"><i>Neoth Elohim/ bears both.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/81\" target=\"main\">1673 edition</a> prints these Hebrew glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</span>",
"seek":"<span class=\"annotation\"><i>They seek/ thy Name, Heb.</i>  The <a href=\"http://wwwlib.umi.com/eebo/image/60223/81\" target=\"main\">1673 edition</a> prints these  glosses in the margins.  Their presence suggests that Milton was concerned with producing a fairly strict translation, one that would be widely accepted and used for common worship.</p></div></body> </html> </span>"}
