var annotList = {"prima":"<span class=\"annotation\"><i>De Idea Platonica.</i>  <a href=\"text.shtml\" target=\"text\">English translation.</a>  Back to <a href=\"latin.shtml\" target=\"text\">Latin text.</a>  Open <a href=\"latin.shtml\" target=\"new_window\">Latin text in new window.</a></p><p class=\"first\"></span>",
"intro":"<span class=\"annotation\"><i>Introduction</i>. Milton titled this collection of Latin and Greek verses, \"Sylvarum,\" or \"of the woods,\" indicating the variety of metrical forms included, even a variety of languages, since two are in Greek. The metrical forms employed here include iambics, hexameters and various kinds of Horatian modes, including <a href=\"http://en.wikipedia.org/wiki/Alcaic_stanza\" target=\"main\">alcaic stanzas</a>. Milton arranged the poems in a roughly chronological order according to their dates of composition, probably to emphasize his progress as a poet from his earliest attempts to his more mature poems.</p><p class=\"next\">  On July 2, 1628, Milton wrote to Alexander Gil, his former tutor and enclosed with his letter a printed copy of a poem he composed for an \"Academic Assembly.\"  This was probably Cambridge\'s commencement exercise held on July 1 that year.  Milton wrote: \"by chance a certain Fellow of our House, who was going to act as Respondent in the Philosophical Disputation at this Academic Assembly, entrusted to my Puerility the Verses which annual custom requires to be written on the questions, he himself being long past light-minded nonsense of that kind and more intent on serious things\" (<a href=\"../../bibliography/t-z/text.shtml#yale\" target=\"main\"><span class=\"booktitle\">Complete Prose Works</span></a> 1.314).  This poem, or \"Naturam non pati senium\" may be the verses to which Milton referred in that letter.</p><p class=\"next\">The poem mildly mocks its speaker, a naive follower of Aristotle, and so aligns Milton with the tradition of humanist platonism that ridiculed medieveal schlasticism.</p><p class=\"next\">The translation follows that of <a href=\"../../bibliography/l-m/text.shtml#mackellar_latin\" target=\"main\">Walter MacKellar</a> with a few changes based on consulting <a href=\"../../bibliography/n-q/text.shtml#columbia_milton\" target=\"main\">The Columbia Milton</a> and <a href=\"../../bibliography/f-h/text.shtml#hughes\" target=\"main\">Merritt Y. Hughes</a>.</span>",
"ninefold":"<span class=\"annotation\"><i>the ninefold deity.</i>  That is, the muses, daughters of Zeus and Mnemosyne, according to Hesiod\'s <a href=\"http://www.perseus.tufts.edu/cgi-bin/ptext?lookup=Hes.+Th.+29\" target=\"main\"><span class=\"booktitle\">Theogony</span> 36</a>-103.</span>",
"eternity":"<span class=\"annotation\"><i>Eternity.</i>  Milton alludes to Boccaccio\'s personification of Eternity in <span class=\"booktitle\">Genealogy of the Gentile Gods</span> 1.2.</span>",
"seer":"<span class=\"annotation\"><i>The Dircean seer.</i>  Tiresias, who was blinded by Juno, but granted prophetic powers by Zeus; see Ovid\'s <a href=\"http://www.perseus.tufts.edu/cgi-bin/ptext?lookup=Ov.+Met.+3.314\" target=\"main\"><span class=\"booktitle\">Metamorphoses</span> 3.314</a>-36.</span>",
"hermes":"<span class=\"annotation\"><i>Pleione\'s grandchild.</i>  Hermes\'s mother was Maia, one of the Pleiades and the daughter of the sea-nymph Pleione.</span>",
"belus":"<span class=\"annotation\"><i>Belus of old time.</i>  The Assyrian Bel, identified with Baal in <a href=\"../../pl/book_1/text.shtml#line420\" target=\"main\"><span class=\"booktitle\">Paradise Lost</span> 1.422</a>.</span>",
"hermes3":"<span class=\"annotation\"><i>thrice-great Hermes.</i>  Hermes Trismegistus (three times great), traditionally the author of the <a href=\"http://www.levity.com/alchemy/corpherm.html\" target=\"main\"><span class=\"booktitle\">Corpus Hermeticum</span></a>, a body of mystical writings dating from sometime in the first three centuries of the Common Era.  Neoplatonists of the Renaissance regarded Hermes as knowing everything.  See the <span class=\"booktitle\">Britannica</span> article for more on <a href=\"http://www.search.eb.com/eb/article?eu=115000\" target=\"main\">hermeticism,</a> ancient and early modern.</span>",
"plato":"<span class=\"annotation\"><i>the Academy.</i>  Plato\'s Academy.</p></div></body></html></span>"}
