var annotList = {"numbers":"<span class=\"annotation\"><i>Sonnets 18, 19, 20, 21, and 23</i>  were numbered XV., XVI., XVII., XVIII., and XIX., respectively in <a href=\"http://wwwlib.umi.com/eebo/image/60223/34\" target=\"main\"><span class=\"booktitle\">Poems</span> (1673)</a>.</span>",
"intro":"<span class=\"annotation\"><i>Introduction.</i>  Dates ranging from 1651 to 1655 have been suggested for this sonnet, but Barbara Lewalski\'s recently articulated case for late in 1652 appears to agree best with the few clues available (<a href=\"../../bibliography/l-m/text.shtml#barbara_lewalski\" target=\"main\"><span class=\"booktitle\">The Life of John Milton</span></a> 289).  The sonnet\'s second line has often led readers to assume an earlier date because no one in the seventeenth century would express confidence about living much past 70, if that.  If he wrote this line in 1652, he would be counting on 86 years.  Milton\'s own father lived to be at least 84.  Lewalski also reminds us that Milton often understated his age and predated several poems in the 1645 <span class=\"booktitle\">Poems</span>.  He was anxious about his age and his personal attractiveness.  He was also anxious about vocational belatedness.  By 1652 Milton was totally blind.  He had spent years fulfilling his duties to the Council of State.  Now he was under malicious attack for defending Cromwell\'s government to the world and for his own advocacy of divorce.  The anonymous <span class=\"booktitle\">Regia Sanguinis Clamor ad C&oelig;um Adversus Parracidas Anglicanos</span> (The Hague, 1652) even ridiculed his blindness (see <a href=\"../../bibliography/l-m/text.shtml#barbara_lewalski\" target=\"main\">Lewalski</a> 289).  He had always meant to write a great English epic, and now it must have seemed impossible.  If he worried about belatedness at his twenty-fourth birthday (<a href=\"../sonnet_7/text.shtml\" target=\"main\">\"How Soon Hath Time\"</a>), by age forty-three he must have been tempted to bitterness and despondency.  This brilliant sonnet is proof enough that his talent has not been rendered \"useless\" by age and blindness.</span>",
"consider":"<span class=\"annotation\"><i>When I consider.</i> Shakespeare\'s <a href=\"http://www.cs.usyd.edu.au/~matty/Shakespeare/texts/poetry/sonnets\" target=\"main\">Sonnet 15</a> contains a similar first line (find \"When I consider\").</span>",
"blindness":"<span class=\"annotation\"><i>dark world and wide.</i>  Milton further mourns his loss of sight in <a href=\"http://www.dartmouth.edu/~milton/reading_room/pl/book_3/text.shtml#blind\" target=\"main\"><span class=\"booktitle\">Paradise Lost</span> 3.22</a>-55 and <a href=\"../sonnet_22/text.shtml\" target=\"main\">Sonnet 22 1-5</a>.</span>",
"talents":"<span class=\"annotation\"><i>one Talent.</i>  See the parable of the talents in <a href=\"http://www.biblegateway.com/bible?passage=Matthew+25&amp;version=KJV\" target=\"main\">Matthew 25</a>:14-30.</span>",
"daylabour":"<span class=\"annotation\"><i>day labour.</i>  See the parable of the bridegroom in <a href=\"http://www.biblegateway.com/bible?passage=Matthew+25&amp;version=KJV\" target=\"main\">Matthew 25</a>:1-13 and also <a href=\"http://www.biblegateway.com/bible?passage=John+9&amp;version=KJV\" target=\"main\">John 9:</a>4.</span>",
"fondly":"<span class=\"annotation\"><i>fondly.</i>  Foolishly.  See <a href=\"http://www.oed.com/\" target=\"main\"><span class=\"booktitle\">OED2</span></a>.</span>",
"yoak":"<span class=\"annotation\"><i>milde yoak.</i>  Jesus states \"For my yoke is easy, and my burden is light\" in <a href=\"http://www.biblegateway.com/bible?passage=Matthew+11&amp;version=KJV\" target=\"main\">Matthew 11</a>:30. </span>",
"thousands":"<span class=\"annotation\"><i>Thousands at his bidding.</i>  <a href=\"http://www.biblegateway.com/bible?passage=Psalms+68&amp;version=KJV\" target=\"main\"> Psalm 68</a>:17 and <a href=\"http://www.biblegateway.com/bible?passage=Zechariah+1&amp;version=KJV\" target=\"main\">Zechariah 1</a>:10 mention the activity of God\'s servants on Earth.</p></div></body></html></span>"}
